### ISSUE TITLE
should we use react?

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/rooch#2]
some people have expressed concerns about using `preact`. This package is not for me so I don't really care. What do folks think?

**Comment by jongacnik** [comment]
@yoshuawuyts old thread but as I was working on [a rooch update](https://github.com/jongacnik/rooch/tree/2.0.0) I had some thoughts. I think `preact` is still a better fit. Seems like team react is [realllly pushing](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html) es6 features and also deprecating `React.createClass` and `React.createElement`, which we need for template string style. 

i tried dropping react in yesterday just as a test and lotsa warnings and errors ensued, didn’t seem worth the trouble to sort out. `preact` + `preact-compat` when needed seems good enough to me!
